// <auto-generated />
using System;
using DigitalPortfolio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalPortfolio.API.Migrations
{
    [DbContext(typeof(DigitalPortfolioDbContext))]
    [Migration("20240619030508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalPortfolio.API.Models.AchievementModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconSVG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.LikeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.AchievementModel", b =>
                {
                    b.HasOne("DigitalPortfolio.API.Models.UserModel", null)
                        .WithMany("Achievements")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.LikeModel", b =>
                {
                    b.HasOne("DigitalPortfolio.API.Models.UserModel", null)
                        .WithMany("Likes")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.ProjectModel", b =>
                {
                    b.HasOne("DigitalPortfolio.API.Models.UserModel", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("DigitalPortfolio.API.Models.UserModel", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Likes");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
